### ISSUE TITLE
erreur brûleur non signalée

### ISSUE THREAD

**Issue by Jack59510** [PhilippeJ-code/viessmann#1]
Bonjour,

Je viens d'installer le plugin Viessmann, il fonctionne à merveille.
Par contre ma chaudière a eu un souci de brûleur (erreur brûleur D1) mais cela n'a pas été remonté par le plugin. Aucune information de disfonctionnement.

Serait il possible d'implémenter cette remontée d'erreur?

Merci d'avance

**Comment by PhilippeJ-code** [comment]
Bonjour,

Le plugin ne remonte pas les erreurs mais ça peut s'envisager, je regarde à ça

Philippe

**Comment by Jack59510** [comment]
Philippe, merci et bravo pour cette réactivité, but

Mis à Jour avec la version du 19-02-2021

Petits soucis de fonctionnement, voir ci dessous:


[viessmann.txt](https://github.com/PhilippeJ-code/viessmann/files/6015146/viessmann.txt)


Pas le feu au lac

**Comment by PhilippeJ-code** [comment]
Bonjour, nous sommes plusieurs à avoir eu l'erreur à peu près au même moment. Je soupçonne un problème sur le serveur 
Viessmann, vous avez encore l'erreur pour le moment.  ?

Philippe

**Comment by PhilippeJ-code** [comment]
Pour les valeurs trop longues, il faut regarder dans les valeurs historisées s'il n'y a pas une valeur trop longue pour l'historisation. Il y a une limite de taille imposée par Jeedom.

Philippe

**Comment by Jack59510** [comment]
Plus de timeout, bonne intuition.
Pour SQL j'ai réduit l'historisation à seulement 2 éléments: temp extérieur
et temp pièce et ça fonctionne bien.

Pour ce qui est des erreurs, c'est l'historique qui est affiché/remonté,
est ce qu'il n'y aurait pas par hasard la possibilité d'afficher l'état
réel de la chaudière (OK/Default)?

Merci pour tous les efforts, ce plugin est vraiment sympathique.

Jacques

Le sam. 20 févr. 2021 à 16:26, PhilippeJ-code <notifications@github.com> a
écrit :

**Comment by Jack59510** [comment]
Bonjour Philippe, 

Le fichier d'erreurs est bien remonté mais ce qui serait super c'est afficher le statut live de la chaudière quand il y a un défaut. 
Par exemple lorsque ma chaudière a un défaut de bruleur (D1 en l'occurence) 
Y a t'il moyen par exemple d'afficher un petit sens interdit lorsque la chaudière est en panne (avec le code panne si possible)?

Autre chose aussi, à chaque mise à jour du plugin, les commandes sont réarrangées par défaut, ce qui oblige à reprendre la personnalisation, je ne sais pas si c'est possible d'éviter cela.

En tout cas merci pour les évolutions du plugin, beau travail.

**Comment by PhilippeJ-code** [comment]
Bonjour,

Vous pourriez m'envoyer une copie d'écran avec les infos de dysfonctionnement que je vois comment je pourrais déduire le statut live de la chaudière.

Pour les commandes, je regarde

Philippe

**Comment by Jack59510** [comment]
Snapshots Côté VICARE
Snapshot du Dashboard quand la chaudière est HS (on voit le circulateur OFF
el le Brûleur ON alors qu'il est éteint)

Bonne réception

Le ven. 5 mars 2021 à 11:42, PhilippeJ-code <notifications@github.com> a
écrit :

**Comment by Jack59510** [comment]
contenu de la commande "erreur":
AN;2021-03-05 09:22:23;d1;AC;2021-03-05 09:22:23;d1;HN;2021-03-05
09:21:33;d1;HC;2021-03-05 09:21:33;d1;HC;2021-03-04
06:01:02;d1;HC;2021-02-27 06:01:44;d1;HC;2021-02-26
06:01:06;d1;HC;2021-02-25 05:31:24;d1;HC;2021-02-24
14:28:11;d1;HC;2021-02-22 06:01:11;d1

Le ven. 5 mars 2021 à 13:42, Jacques Devau <jacques.devau@gmail.com> a
écrit :

**Comment by PhilippeJ-code** [comment]
Voilà, c'est fait et j'ai poussé la modification sur le market. Si vous voulez bien tester et me faire un retour

Dites-moi aussi si l'ordre des commandes est affecté par la mise à jour du plugin

**Comment by Jack59510** [comment]
Nettement plus confortable, mes commandes sont regroupées en bas mais leur ordre n'est pas modifié. (juste 2 intrus les sliders parallèle et pente qui se sont immiscés après la commande "rafraichir", vraiment rien.
J'envoie les snapshots
De mon côté je vais tester les nouvelles commandes disponibles avec cette version.
![chaudière avant update](https://user-images.githubusercontent.com/49286158/110139171-09bec200-7dd3-11eb-813b-01d559f5a802.JPG)
![chaudière après update](https://user-images.githubusercontent.com/49286158/110139287-2bb84480-7dd3-11eb-8c9f-d7159d3e5122.JPG)
[chaudière commandes.xlsx](https://github.com/PhilippeJ-code/viessmann/files/6091610/chaudiere.commandes.xlsx)


Merci

**Comment by Jack59510** [comment]
Philippe, on se rapproche de la perfection.
L'erreur courante fonctionne très bien, un must.
Encore bravo.
![chaudière D1](https://user-images.githubusercontent.com/49286158/110237733-d187c280-7f3d-11eb-8f1e-f9ccc2704468.JPG)

**Comment by Jack59510** [comment]
Ce ticket peut évidemment être clos.
Encore merci. 
Jacques
