### ISSUE TITLE
fioul

### ISSUE THREAD

**Issue by VieuxEd** [PhilippeJ-code/viessmann#2]
Bonjour
le plugin semble ne pas fonctionner pour les chaudières au fioul (vitorondens 200) : j'ai acheté vitonnect juste pour ca !
serait ce possible de prendre en charge les chaudières fioul ?

On me dit "Property "value" was not found." et le plugin ne récupère que certaines données, pas toutes...

un grand merci d'avance ! :) et un grand bravo pour ce superbe plugin !

EP

**Comment by PhilippeJ-code** [comment]
Bonjour,

Je travaille sur une nouvelle version qui prend en compte les différences entre les informations reçues et celles réellement disponibles. En attendant cette nouvelle version, je regarde à une solution qui vous conviendra, je vous tiens au courant

Philippe

**Comment by VieuxEd** [comment]
Super merci Philippe !
Dites moi si je peux aider à tester quelque chose ! (ou donner accès à ma plateforme si besoin)
Thanks !
EP

**Comment by PhilippeJ-code** [comment]
Bonjour,

Si vous voulez essayer la nouvelle version et me dire si ça résout votre problème

Philippe

**Comment by VieuxEd** [comment]
Bonsoir
Merci pour votre réaction hyper rapide !
J'ai fait quelques tests, résumés dans le .doc joint.
En synthèse tout est ok sauf :
- température extérieure
- relève une température consigne eau chaude là où mon installation ne fait pas l'eau chaude
- pas de suivi consommation du fioul
[Test module Viessmann Jeedom_v20210409.docx](https://github.com/PhilippeJ-code/viessmann/files/6287653/Test.module.Viessmann.Jeedom_v20210409.docx)

Un grand merci !

**Comment by PhilippeJ-code** [comment]
Bonsoir,

Pour la température extérieure, je mets 99 quand la température n'est pas disponible dans ce cas là je ne l'afficherai pas, ce sera plus clair.

Pour l'eau chaude, je vais ajouter une option pour permettre l'affichage ou pas de la tuile comme pour le gaz et l'électricité

La consommation fioul, c'est disponible dans Vicare ?

J'envoie une nouvelle version

**Comment by VieuxEd** [comment]
Bonsoir,

La température est bien présente dans ViCare, disponible depuis une sonde extérieure viessmann associée à l'installation : ca doit être possible de récupérer l'info ?

Pour ce qui est de la consommation de fioul vous avez raison cette information n'est pas disponible.
En revanche on a la consommation horaire, peut être produire un histogramme/ une courbe présentant la durée quotidienne vs température extérieure ? 
Je dis ca ... ce ne sont que des idées :)

Encore merci !
++
EP

**Comment by PhilippeJ-code** [comment]
Bonjour,

J'aurais besoin des informations disponibles sur votre chaudière, pour cela il faut aller dans la configuration du plugin et dans le champ Log Possibilités mettre la valeur à Oui ( avec un O majuscule ), sauvegarder et demander un rafraichissement des données de la chaudière, puis aller dans le log Viessmann récupérer les infos qui auront été loggées et me les envoyer.

Philippe

**Comment by VieuxEd** [comment]
Bonjour,

J'ai procédé comme suit :
- Log équipement = Oui ("O" ne donne rien)
- Log & surveillance module = debug
- je rafraichis l'équipement
- log viessmann = cf fichier joint
[viessmann.txt](https://github.com/PhilippeJ-code/viessmann/files/6289567/viessmann.txt)

Ceci dit apres vérification, il semble bien, vous avez raison, que ViCare ne récupère pas la donnée température extérieure de la sonde, mais récupère des données de localisation... On a bien une température extérieure mais pas celle de la sonde :)

**Comment by PhilippeJ-code** [comment]
ça n'a pas fonctionné, on devrait avoir un log avec des lignes du genre, le log du plugin est bien en mode debug ?

[2021-04-10 09:39:18][DEBUG] : heating.circuits.0.heating.curve::slope --> 1.8

**Comment by VieuxEd** [comment]
effectivement voila le log avec les éléments
[viessmann (2).txt](https://github.com/PhilippeJ-code/viessmann/files/6290347/viessmann.2.txt)

**Comment by PhilippeJ-code** [comment]
Bonjour,

Désolé mais je ne vois rien dans le log qui me permettrait de récupérer la consommation de fioul.

Philippe

**Comment by VieuxEd** [comment]
Bonjour

oui tout à fait vous avez raison, c'est ce que je mettais dans un précédent message.
en fait ca compte les heures, et de là, en fonction de la consommation heure on peut dériver la consommation...

la chaudière produit l'info pourtant mais elle n'est pas remontée dans vicare.

un grand merci en tout cas pour cette mise à jour personnalisée :)
