### ISSUE TITLE
Reason: FEATURE_NOT_FOUND

### ISSUE THREAD

**Issue by Xalio** [PhilippeJ-code/viessmann#3]
Bonjour,
merci pour ce plugin Viessmann!
Lors de l'installation sur Jeedom j'ai reçu l'erreur suivante "Reason: FEATURE_NOT_FOUND" quand j'ai essayé de modifier la temperature de chauffage.

La température extérieure et de l'eau chaude remontent mais pas celle du chauffage. L'application mobile Vicare fonctionne bien de son côté.

Savez vous pourquoi cette erreur peut arriver?

Merci
Nicolas
<img width="1538" alt="Screenshot 2021-04-13 at 10 56 03" src="https://user-images.githubusercontent.com/774362/114526002-e34c3c00-9c46-11eb-8663-053763b6c712.png">
![IMG_0734](https://user-images.githubusercontent.com/774362/114526242-17276180-9c47-11eb-8ae3-4f9085f808f2.PNG)

**Comment by PhilippeJ-code** [comment]
Bonjour,

Probablement que la température de consigne n'a pas le même nom sur votre chaudière.

Pour vérifier, vous pouvez faire les opérations suivantes

  Dans la configuration du plugin, activer le mode debug
  Dans la configuration de l'équipement, mettre Oui dans l'option Log Possibilités ( Oui avec un O majuscule ) et sauvegarder
  Rafraichir les données
  Consulter le log du plugin, l'exporter et me l'envoyer, je regarderai

Philippe

**Comment by Xalio** [comment]
Merci Philippe, hier j'avais pris les logs en Debug et j'avais juste oublié de les attacher au ticket... les voici.
Merci
[viessmann.log](https://github.com/PhilippeJ-code/viessmann/files/6310803/viessmann.log)

**Comment by PhilippeJ-code** [comment]
Bonjour,

Votre chaudière utilise le circuit 1, dans la configuration du plugin mettre 1 dans le champ "id du circuit"

Philippe

**Comment by Xalio** [comment]
Parfait! Merci ça fonctionne.
